os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '12'
  - '14'
  - '16'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
script:
  - 'npm run test:unit'
  - 'export DEBUG=testing:*'
  - 'npm run test:integration'
