version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: ''
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - npm install
  - echo %cd%
  - node --version
  - npm --version
test_script:
  # Package tests fail for now because materialize is not supported
  # - npm run test:package
  - npm run test:unit
  - export DEBUG=testing:*
  - npm run test:integration
build: 'off'
